spring:
    datasource:
        password: ${POSTGRES_PASSWORD}
        platform: postgres
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
        username: ${POSTGRES_USER}
        driverClassName: org.postgresql.Driver
flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-on-validation-error: false
    cleanDisabled: true
logging:
    level:
        root: INFO
#    pattern:
#        console: "%white(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
#        file: "%white(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
